In [1]:
import os
import sys
import tester_1

In [2]:
%load_ext autoreload
%autoreload 2

In [73]:
%reload_ext autoreload
%autoreload 2

## Enter a number between 1 and 1000 for the total robot movements for exploring maze until reset. Leave blank for default = (maze_dim + 2)^2.
### Better to use COVERAGE_RESET_THRESHOLD instead.

In [83]:
os.environ['MOVEMENT_RESET_THRESHOLD'] = ''

## Enter a percentage (1 - 100) of the maze to map before reset. To reset the robot once the goal is found enter 'goal'.

In [36]:
os.environ['COVERAGE_RESET_THRESHOLD'] = '85'

In [ ]:
os.environ['COVERAGE_RESET_THRESHOLD'] = 'goal'

## Enter a strategy to use for mapping the maze: 'random', 'avoid dead ends', 'smart map'. Leave blank for default = 'smart map'

In [55]:
os.environ['MAP_STRATEGY'] = 'random'

In [60]:
os.environ['MAP_STRATEGY'] = 'avoid dead ends'

In [61]:
os.environ['MAP_STRATEGY'] = 'smart map'

## Set TEST_REPORT to True if you want tester_1.py to return reporting on performance. Default is False.

In [11]:
os.environ['TEST_REPORT'] = 'False'

In [16]:
os.environ['TEST_REPORT'] = 'True'

In [17]:
%run tester_1.py test_maze_03.txt

Movement reset threshold set to default = 324.
Coverage reset threshold set to default = goal.
Maze map strategy used is smart map.

Starting run 0.

Found Goal in 168 moves.
Percent of cell walls mapped until goal found is 81%.

Number of walls mapped per cell:
[3  3  3  4  4  4  4  4  3  2  1  1  1  1  1  2]
[1  2  2  4  4  4  4  4  4  3  0  0  0  0  0  1]
[1  0  2  4  4  4  4  4  4  4  3  3  4  2  2  2]
[1  0  1  4  4  4  4  4  4  4  4  4  4  3  3  4]
[1  0  0  1  2  2  4  4  4  4  4  4  4  4  4  4]
[1  0  0  0  1  2  4  4  4  4  4  4  4  4  4  4]
[1  0  1  2  4  4  4  3  4  4  4  4  4  4  4  4]
[1  1  4  4  4  4  4  0  3  4  4  4  4  4  4  4]
[1  0  3  4  3  4  4  3  4  4  4  4  4  4  4  4]
[1  2  4  4  1  3  4  4  4  4  4  4  4  3  4  4]
[1  1  4  4  2  1  4  4  4  4  4  4  2  4  4  4]
[3  3  4  4  4  2  1  3  4  4  4  4  3  1  3  4]
[4  4  4  4  4  4  3  3  4  4  4  4  4  4  4  4]
[4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4]
[4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4]
[4

## Use the command below to open a window that overlays the goal route onto the maze.

Either Jupyter or Anaconda is not able to re-open the turtle window with repeated calls. So, it has to be run through the command shell.

Click on turtle window to close it.

In [12]:
!python tester_1.py test_maze_02.txt showroute

Movement reset threshold set to default = 256.
Coverage reset threshold set to default = goal.
Maze map strategy used is smart map.

Starting run 0.
Ending first run. Starting next run.
Starting run 1.
Goal found; run 1 completed!
Task complete! Score: 35.533


In [43]:
maze_dim = 12
goal_bounds = [maze_dim/2 - 1, maze_dim/2]

directions = ['u','r','d','l']
count = 0

In [62]:

for i in goal_bounds:
    for j in goal_bounds:
        count = 0
        for k,v in maze_map[(i,j)].iteritems():
            if v == 0:
                count += 1
        if count == 1:
            print i,j

r 1
u 1
d 0
l 0
r 2
u 0
d 1
l 0
r 0
u 1
d 0
l 1
r 1
u 0
d 1
l 1
6 6


In [64]:
import maze_1

In [68]:
testmaze = maze_1.Maze('test_maze_01.txt')

In [69]:
maze_map = testmaze.make_map()

In [70]:
goal_door = testmaze.goal_door(maze_map)
goal_door

(6, 6)

In [45]:
import numpy

In [ ]:
open_dirs = [k for k,v in self.maze_map[self.location].iteritems() if k != dir_reverse[self.heading] and v != 0]

In [71]:
import solve_maze

In [96]:
%run solve_maze test_maze_01.txt

[-  -  -  -  -  -  -  -  -  -  -  -]
[-  -  -  -  -  -  -  -  -  -  -  -]
[-  -  -  -  -  -  -  -  -  -  -  -]
[-  -  -  -  -  -  -  -  -  -  -  -]
[-  -  -  -  -  -  -  -  -  -  -  -]
[-  -  -  -  -  -  G  L  -  -  -  -]
[-  -  -  -  -  -  -  R  L  -  -  -]
[-  -  -  -  -  -  -  -  #  -  -  -]
[-  -  -  -  -  -  -  -  R  #  #  L]
[R  R  -  -  R  #  R  -  -  -  -  #]
[#  #  -  -  #  -  L  R  -  -  -  #]
[S  L  #  #  L  -  -  L  #  #  #  L]


In [97]:
!python solve_maze.py test_maze_03.txt showroute